name: "PR to Main"
on:
  pull_request:
    branches:
      - main

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: switch-case
        with:
          default: "its the default"
          conditionals-with-values: |
            ${{ 'test' == 'not-test' }} => shouldnt be this one
            ${{ 'test' == 'test' }} => correctAnswer
          
      - run: echo ${{ steps.switch-case.outputs.value }}
      
      # Optionally fail the workflow, should you choose
      - name: Fail on non-correct answer
        if: ${{ steps.switch-case.outputs.value != 'correctAnswer' }}
        run: 'echo "No version change :/" && exit 1'
  
  auto-approve-pr:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'dkershner6'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
